name: CLI

on:
  push:
    paths: ['cli/**', '.github/workflows/cli.yml']
  pull_request:
    paths: ['cli/**', '.github/workflows/cli.yml']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eth-library/nix-aerie-python:latest
    steps:
      - uses: actions/checkout@v4
      # activates nix flakes shell via .envrc
      - uses: eth-library/nix-aerie/.github/actions/direnv-run@main
        with:
          command: dap check --scope cli
